[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "biomass2pred"
version = "0.1.0"
description = "Biomass prediction from images"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pandas",
    "timm",
    "pathlib",
    "scikit-learn"
]

[project.optional-dependencies]
torch = [
    "torch",
    "torchvision",
    "torchaudio"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
