project:
  name: biomass2prediction
  seed: 7
  run_name: effnet_b2_baseline

data:
  images_root: data
  train_csv: data/train_split.csv
  valid_csv: data/val_split.csv

  target_names:
    - Dry_Clover_g
    - Dry_Green_g
    - Dry_Dead_g

  image_size: [256, 256]

dataloader:
  batch_size: 32
  num_workers: 0

model:
  backbone: efficientnet_b2
  pretrained: true

train:
  epochs: 100
  lr: 0.0003
  weight_decay: 0.0001
  output_dir: outputs/runs
  unfreeze_at_epoch: 85
  lr_multipliers:
    head: 0.1
    classifier: 1

loss: mse

optimizer: adamw
